name: nymea-networkmanager
version: 0.1.0
summary: Daemon for setup wireless connection using Bluetooth LE. 
description: |
  The nymea-networkmanager daemon provides a Bluetooth Low Energy server and
  allowes to configure the wireless network using the network-manager DBus connection.
  The default behaviour of the daemon is the offline mode. If the device is not connected
  to any LAN or WLAN connection, the Bluetooth server will start. Once the device is
  connected to a network, the Bluetooth server will shut down automatically. The advertise name
  is 'BT WLAN setup'.

grade: stable
confinement: strict

apps:
  nymea-networkmanager:
    command: env PATH=$PATH:$SNAP/bin qt5-launch nymea-networkmanager -a "BT WLAN setup" -m offline
    daemon: simple
    restart-condition: always
    plugs:
      - bluez
      - bluetooth-control
      - network-manager

parts:
  # nymea-networkmanager
  nymea-networkmanager:
    plugin: qmake
    source: https://github.com/guh/nymea-networkmanager.git
    source-type: git
    build-attributes: [keep-execstack]
    source-branch: master
    project-files: [ nymea-networkmanager.pro ]
    after: [ qt-5-11-1 ]


  # Custom launcher to support also armhf
  qt5-launch:
    plugin: dump
    build-attributes: [keep-execstack]
    source: snap/
    organize:
      qt5-launch: bin/


  # Qt 5.11.1 
  qt-5-11-1:
    plugin: autotools
    source: http://download.qt.io/archive/qt/5.11/5.11.1/single/qt-everywhere-src-5.11.1.tar.xz
    source-type: tar
    build-attributes: [keep-execstack]
    build-packages:
      - g++
      - freetds-dev
      - gdb
      - libatspi2.0-dev
      - libdbus-1-dev
      - libsystemd-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgbm-dev
      - libgles2-mesa-dev
      - libglib2.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libharfbuzz-dev
      - libicu-dev
      - libinput-dev
      - libmtdev-dev
      - libmysqlclient-dev
      - libpcre3-dev
      - libpq-dev
      - libproxy-dev
      - libsqlite3-dev
      - libssl-dev
      - libudev-dev
      - libbluetooth-dev
      - libxext-dev
      - libxi-dev
      - pkg-kde-tools
      - publicsuffix
      - unixodbc-dev
      - zlib1g-dev
    configflags:
      - -release
      - -confirm-license
      - -opensource
      - -platform 
      - linux-g++
      - -openssl
      - -syslog
      - -journald
      - -no-rpath
      - -verbose
      - -silent
      - -no-gif
      - -no-libpng
      - -no-libjpeg
      - -no-opengl
      - -no-widgets
      - -no-xcb
      - -no-gtk
      - -no-fontconfig
      - -no-eglfs
      - -no-cups
      - -no-accessibility
      - -no-use-gold-linker
      - -nomake 
      - examples
      - -nomake 
      - tests
      - -skip 
      - qt3d
      - -skip 
      - qtactiveqt
      - -skip 
      - qtandroidextras
      - -skip 
      - qtcanvas3d
      - -skip 
      - qtcharts
      - -skip 
      - qtdatavis3d
      - -skip 
      - qtdeclarative
      - -skip 
      - qtdoc
      - -skip 
      - qtgamepad
      - -skip 
      - qtgraphicaleffects
      - -skip 
      - qtimageformats
      - -skip 
      - qtlocation
      - -skip 
      - qtmacextras
      - -skip 
      - qtmultimedia
      - -skip 
      - qtpurchasing
      - -skip 
      - qtquickcontrols
      - -skip 
      - qtquickcontrols2
      - -skip 
      - qtremoteobjects
      - -skip 
      - qtscxml
      - -skip 
      - qtsensors
      - -skip 
      - qtserialbus
      - -skip 
      - qtserialport
      - -skip 
      - qtspeech
      - -skip 
      - qtsvg
      - -skip 
      - qtvirtualkeyboard
      - -skip 
      - qtwayland
      - -skip 
      - qtwebchannel
      - -skip 
      - qtwebengine
      - -skip 
      - qtwebglplugin
      - -skip
      - qtwebsockets
      - -skip 
      - qtwebview
      - -skip 
      - qtwinextras
      - -skip 
      - qtx11extras
      - -skip 
      - qtxmlpatterns
    stage-packages:
      - icu-devtools
      - libc6
      - libdbus-1-3
      - libdrm2
      - libfreetype6
      - libgbm1
      - libgcc1
      - libglib2.0-0
      - libharfbuzz0b
      - libice6
      - libinput10
      - libmtdev1
      - libpcre16-3
      - libproxy1v5
      - libsm6
      - libsqlite3-0
      - libstdc++6
      - libudev1
      - libxext-dev
      - libxi6
      - perl
      - zlib1g
      - libdouble-conversion-dev
